### PR TITLE
BOX-3_LVGL9_UI_Demo

### PR DESCRIPTION
**Pull request by 0015**
- ESP32-S3-BOX-3
- LVGL 9
Added UI part to existing example. Thanks for sharing a great library.

### CODE REVIEW

**Comment by jmattsson** [comment]
Ooh, neat! I wish I had a box-3 to test this on!

Is there a particular reason why you initialise/shutdown on each TTS event? Generally I would avoid doing that seeing as the TTS requires a large memory allocation which could become impossible if the memory has become fragmented enough. Initialising on startup avoids that particular risk.

**Comment by 0015** [comment]
@jmattsson First of all, thank you for creating a great library. It makes it very easy to implement a standalone version of TTS. The reason I repeated the initialization and shutdown in triggerTTS() is because this was the only way it worked. I also tried picotts_add() on the event without init/shutdown, but the TTS was not triggered. If you can tell me the specifics about this, I will fix it. Thanks.

**Comment by jmattsson** [comment]
Thank you! I'd been waiting on Espressif to release their own TTS engine, but grew fed up with waiting 🙃

That should certainly work. In my experience the trailing '\0' is needed to kick off the TTS — is it possible you weren't including it in your call to `picotts_add()`? (you're clearly doing it now)

**Comment by jmattsson** [comment]
If you want you can have a look at the toy project I built: https://github.com/DiUS/esp-joker

**Pull request closed without merging**
